### PR TITLE
Added mobile responsiveness to the whole page

### LINKED ISSUE #213: Slides on SMP website not mobile friendly
**Description**
At a certain screen size the slides on the SMP website get cut off. Also the logo of CNCF is not mobile friendly

**Expected Behavior**
both should be friendly in every screen size

**Screenshots**
CF7FE353-407F-4C63-94B3-1A72D3969192_1_105_c

**Environment:**
 - OS: MacOS
 - Browser:  Chrome, Safari

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
fixed mobile responsive issues of nav-bar, google slides and code snippet.

This PR fixes #213 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@nikhilsharma03... will you review?

**Comment by leecalcote** [comment]
// @Vineet-Sharma29

**Comment by leecalcote** [comment]
Calling all Sharmas! 😉

**Review by Jashpatel1 — COMMENTED** [review]
@warunicorn19 Nice work here. Just a thing to add. If you are aiming to bring responsiveness to the entire page do you mind working on the footer as well?
Screenshot from 2021-07-24 21-57-54

**Comment by warunicorn19** [comment]
Actually I've created a seperate issue for it, but I don't mind doing it myself. On it @Jashpatel1

**Comment by NikhilSharma03** [comment]
Looks fine to me :+1: . Great work @warunicorn19.

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks @warunicorn19

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
