### PR TITLE
[SITE] Implementation of Dashboard Page

### LINKED ISSUE #272: New SMP DashBoard
**Current Behavior**

So service Mesh Performance shows rich performance profiles and realtime tests results, but there   is a need of the dashboard for the SMP where results are analysed and charted visually to give better insights to performance results. The current charts are good but are not showing the ample amount of data that the SMP holds power to.

- Design backend for facilitating the dashboard data
- Design frontend for visually appealing dashboard

**Desired Behavior**

Create a new dashboard for Service Mesh Performance. The good context and reference could be SMI Conformance Dashboards

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
This PR will help in tracking the progress of the SMP Benchmark Dashboard page.

This PR updates #272 

**Notes for Reviewers**
This is the basic structure on how the page is going to look, any feedback comments are welcome.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@thebeginner86, batter up.

**Comment by leecalcote** [comment]
Drop an empty state in to the position for where live charts will be shown and we're good to merge, @asubedy

**Review by leecalcote — CHANGES_REQUESTED** [review]
Wait... the lack of reuse in this PR is no bueno. Use `includes` and `layouts`, please.

**Comment by asubedy** [comment]
> Wait... the lack of reuse in this PR is no bueno. Use `includes` and `layouts`, please.

Done, now the page is displayed using `dashboardPage` layout.  // @leecalcote

**Comment by asubedy** [comment]
> Drop an empty state in to the position for where live charts will be shown and we're good to merge, @asubedy

Done ✅ . Added an image from Meshery UI of a dummy performance test result.

**Review by leecalcote — APPROVED** [review]
This is a solid start.

**Pull request merged**
