### PR TITLE
[Dashboard] prototype- card view to display results

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**

This PR fixes #

**Notes for Reviewers**
Just initialization needs additional work

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Is this looks good to you? @asubedy 
https://deploy-preview-327--smp-spec.netlify.app/dashboard

**Comment by Abhishek-kumar09** [comment]
Btw, if you have managed to get the data for service mesh from the scheduled benchmark tests please let me know. I have the test data in there.

**Comment by asubedy** [comment]
> Btw, if you have managed to get the data for service mesh from the scheduled benchmark tests please let me know. I have the test data in there.

Umm I don't have the data from the scheduled benchmark tests, but I do have json file for the test results for the first 25 performance profile.

**Review by leecalcote — APPROVED** [review]

**Comment by Abhishek-kumar09** [comment]
Closing this PR since the first iteration is merged and we can continue working on newer branch.

**Pull request closed without merging**
