### PR TITLE
Adding Screenshot of Performance Test Comparison

### LINKED ISSUE #250: Incorporate screenshot into website
**Current State of the service-mesh-performance site**
The site only has one screenshot of an SMP implementation.

**Desired State of the service-mesh-performance site**
Incorporate this screenshot of a performance test comparison into the site.

SMP comparisons in Meshery

### PR DESCRIPTION
**Pull request by Deepansharora27**
**Description**

This PR fixes #250 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Deepansharora27** [comment]
@warunicorn19 @leecalcote 
Hi 
Can you Kindly Review it ?

**Review by debo19 — COMMENTED** [review]
SharedScreenshot
@Deepansharora27 Can you remove this extra blue margin around the image and make it the same size as the one on top?

**Comment by Deepansharora27** [comment]
Sure @debo19 
I'll do it by today

**Comment by Deepansharora27** [comment]
@debo19 @warunicorn19 
Altering with the Height and Width of the Image and making it look like the top image is not looking so good aesthetically
Although i have removed the extra margin around the Image.
What Shall I do in this Case?

**Comment by warunicorn19** [comment]
@Deepansharora27 okay if it doesn't look good then let's skip it, could you make the commit with the other change, let's have a look.

**Comment by Deepansharora27** [comment]
Sure @warunicorn19 !! Pushing the recent change !!

**Comment by Deepansharora27** [comment]
Done with it @warunicorn19 
Kindly have a look

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @Deepansharora27

**Comment by Deepansharora27** [comment]
Thanks  a lot for your feedback :) @debo19

**Pull request merged**
