### PR TITLE
Updated UI fixed layout of Blogs and Engage Components

### PR DESCRIPTION
**Pull request by mayurjadhav2002**
**Description**

This PR fixes issue #392, the website UI now has fixed height and width for blog components as well as for the resources cards (Engage Component).

**Updated UI** 

Blog Page
Resource Page

**Before Updating** 

Blog Page

Resource page
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by asubedy — CHANGES_REQUESTED** [review]
Great work on the uniformity of cards @mayurjadhav2002, One small chnges, the hover effect on the post cards instead of the content being scaled up let's make the entire card pop up similar to Resources cards.

**Comment by sudhanshutech** [comment]
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by mayurjadhav2002** [comment]
> Let's discuss it on the websites call. Please add this as an agenda item in the meeting minutes, if you would :)
> 
> https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

@sudhanshutech tried to open the link, but getting "Access Denied".

**Comment by mayurjadhav2002** [comment]
@asubedy Hey, thanks for the review, I've applied the changes. also, I want to mention that I have found a new issue on the dashboard page the performance profile table which shows results is not responsive. take a look at the below screenshots. 
**On Desktop**
scrnli_15_08_2023_00-58-57

**On Mobile or Small screen devices**
scrnli_15_08_2023_01-01-06

On **mobile**, it is just showing the profile and endpoints. It is not horizontally scrollable to see other information. 
**What's your view on this?** 
**Can I work on this issue?**  
_if yes then please let me know whether I should need to create a new issue or just solve it in this pr. I guess opening a new issue thread would be more convenient for other users. but please let me know your pov._

Thanks and Regards!

**Review by asubedy — CHANGES_REQUESTED** [review]
@mayurjadhav2002 The same text wrapping effect can be seen in the engage cards too, could you change that too.

**Comment by asubedy** [comment]
@mayurjadhav2002 regarding the dashboard change .YES! that needs a fix you can go ahead and make issue for this and I will assign it to you.

**Comment by mayurjadhav2002** [comment]
@asubedy I have removed the text wrapping effect from engage cards. please let me know if there are any more changes required. in the meantime, I will open a new issue regarding the dashboard page.

**Review by asubedy — APPROVED** [review]
LGTM. Thank you @mayurjadhav2002 🚀

**Pull request merged**
