### PR TITLE
Hyperlink Added to Slide Deck Issue#228

### LINKED ISSUE #228: [Site] Add hyperlink to slide deck
**Current State of the service-mesh-performance site**
The project overview deck is iframe'd on the main project page - https://smp-spec.io
Visitors that want direct access to the presentation, though, aren't provided a link to the presentation.

**Desired State of the service-mesh-performance site**
Add a [hyperlink to the deck](https://docs.google.com/presentation/d/1fm7Eu1T3JSBPVmdFYyyevqQLSmAMLXqzWqC7QxTHGX8/edit#) underneath the iframe'd display of the deck.

### PR DESCRIPTION
**Pull request by Rishi22-Coding**
Signed-off-by: Saptarshi Patra
**Description**
Added Hyperlink to the deck Underneath the iframe'd display of the deck
This PR fixes #228  

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@Rishi22-Coding sorry, there's an existing PR on this issue, why dont you take a look at other issues with the [Help Wanted](https://github.com/meshery/meshery/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. And also, comment on the issue so that someone can assign it to you so that your work doesnt go into vain.😃

**Comment by leecalcote** [comment]
Thank you for this, @Rishi22-Coding. Adding to @warunicorn19's guidance, note that the hyperlink isn't visible.

Screen Shot 2021-08-20 at 1 55 50 PM

Thanks for jumping in. Please do grab another help wanted issue, if you're interested. @warunicorn19 might grab the link that includes all orgs not just the meshery org.

**Comment by warunicorn19** [comment]
[Help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Aservice-mesh-performance+org%3Alayer5io+label%3A%22help+wanted%22+) from all the orgs.

**Comment by Rishi22-Coding** [comment]
Okay sure i will check it out.

**Pull request closed without merging**
