### PR TITLE
Fixing slack notify on star

### PR DESCRIPTION
**Pull request by lohityarra**
Please review it once

**Description**

This PR #246 fixes the [slack.yml] workflow file.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@lohityarra I think you got me a little wrong😅, I meant it'll be exactly like this file https://github.com/meshery/meshery/blob/master/.github/workflows/slack.yml, after copy-pasting the aforementioned file, just change the repo name

**Comment by lohityarra** [comment]
@warunicorn19 I just added the repo name. Sry for the hassle I'll try it again. should I just close this pull request and create a new one?

**Comment by warunicorn19** [comment]
It's no problem😅, you could just add a commit to this branch, no need for a new PR, remember to sign off like you did on this one.

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, Thanks @lohityarra

**Comment by amino19** [comment]
@lohityarra: Whoa, awesome in one go! :rocket: 

**Note:-**
Contributors must have to always write some description, what changes they made at such a bulky repository.
Also, do not forget to attach issue number with `hashtag` as #245

**Comment by lohityarra** [comment]
@amino19 Okay I'll take note of that in the future. Thanks!

**Comment by amino19** [comment]
> @amino19 Okay I'll take note of that in the future. Thanks!

BTW, you can still edit it by clicking on 3 dots at the pull request description & Edit. :slightly_smiling_face:

**Review by sayantan1413 — APPROVED** [review]
LGTM! @lohityarra good work🚀

**Review by akashgp09 — APPROVED** [review]

**Review by navendu-pottekkat — APPROVED** [review]
Thank you @lohityarra 🚀

**Pull request merged**
