### PR TITLE
updated_card_size

### LINKED ISSUE #291: Make card sizes uniform on the site
**Description**
- Cards for resources are not of the same size.
- The blog cards look disorganized.

**Expected Behavior**
- Uniformity of grid sizing
- Equalize the size used in the blog grid (and other grids)

**Screenshots**
grid

cards

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

### PR DESCRIPTION
**Pull request by Akshit42-hue**
Signed-off-by: Axit Patel <patelakshit2025@gmail.com>

**Description**

This PR fixes #291 

**Notes for Reviewers**
I have updated the card size and made it uniform

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
Hey @debo19, please do have a look

**Review by Abhijay007 — COMMENTED** [review]
Resources cards LGTM, blogs cards are also fine if we are considering space, let's wait for others' views on that as well

**Comment by Akshit42-hue** [comment]
Hey @Abhijay007 Thanks for the review

**Comment by debo19** [comment]
@Akshit42-hue Let's take a look at this in the Websites call tomorrow

**Comment by leecalcote** [comment]
> @Akshit42-hue Let's take a look at this in the Websites call tomorrow

Cool

**Comment by Akshit42-hue** [comment]
Update:
Screenshot from 2022-04-13 10-19-22
Does this looks good to you @debo19 @Abhijay007 @leecalcote

**Comment by debo19** [comment]
@Akshit42-hue We don't want the white space around the cards(green). The shadow should be around the images without that space. Also, give some extra padding between the date and bottom of card.

**Comment by Akshit42-hue** [comment]
Required changes have been done please do have a look @Abhijay007 @debo19

**Comment by Akshit42-hue** [comment]
Required changes have been done please do have a look @Abhijay007 @debo19

**Review by Abhijay007 — APPROVED** [review]
@Akshit42-hue it LGTM, let's wait for @debo19 and @leecalcote 's review on this

**Comment by Akshit42-hue** [comment]
Thanks for the update @Abhijay007

**Review by asubedy — CHANGES_REQUESTED** [review]
This looks clean, I would suggest a little bit of spacing between the image and title.

**Comment by Akshit42-hue** [comment]
Required changes have been done @asubedy

**Comment by asubedy** [comment]
Some issue with responsiveness, the cards seem to overlap. Please take a look into this also.
image

**Comment by Akshit42-hue** [comment]
> Some issue with responsiveness, the cards seem to overlap. Please take a look into this also. image

Done

**Review by Abhijay007 — APPROVED** [review]
@Akshit42-hue LGTM

**Comment by Akshit42-hue** [comment]
Please do have a look @debo19, @asubedy

**Review by asubedy — APPROVED** [review]
LGTM 🚀

**Review by debo19 — CHANGES_REQUESTED** [review]
@Akshit42-hue cards look good. The aspect ratio of the images seem to be off now. It was fine till your last set of commits. Can you fix that while you centre align the images. Then we should be good to go.

**Comment by Akshit42-hue** [comment]
Hey @debo19, are you talking about the third image?
If yes, then I can't able to change that .svg image to .png image in index file

**Comment by debo19** [comment]
Screenshot 2022-04-23 at 4 17 07 AM

It's happening to the first 3 images. It might be that you're specifying both height and width together. Changing the image type shouldn't be required.

**Comment by debo19** [comment]
@Akshit42-hue we're almost done here. If you could centre align the images vertically, we'll be good to go

**Comment by Akshit42-hue** [comment]
Hey @debo19, can you please merge this PR so that I can open up an issue

**Comment by leecalcote** [comment]
@Akshit42-hue still working on fixing the vertical alignment?

**Comment by Akshit42-hue** [comment]
> @Akshit42-hue still working on fixing the vertical alignment?

I have tried it but didn't able to  alignment it properly so let's other work on it

**Comment by leecalcote** [comment]
@Akshit42-hue ok, understood. Please close this PR when ready.

**Pull request closed without merging**
