### PR TITLE
corrected alignment of objects

### LINKED ISSUE #263: Wrong alignment of objects in website
**Current State of the service-mesh-performance site**
 Errors in mobile view
 
- [x] Wrong aligning of text with image in `Created with LAYER5 and its open-source community.` 
- [x] Inaccurate alignment of SMP logo in the footer section.
- [x] Wrong alignment of social icons in the footer section.

### Current State in website
Wrong aligning of text with image in `Created with LAYER5 and its open-source community.` 
image
Inaccurate alignment of SMP logo in the footer section.
image
Wrong alignment of social icons in the footer section.
image

**Desired State of the service-mesh-performance site**
I will be changing some of the CSS code in the repository to solve these issues.

### PR DESCRIPTION
**Pull request by akshatnema**
Signed-off-by: akshatnema <20bcs022@iiitdmj.ac.in>**Description**

## Issue
This PR fixes #263.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

### alignment of Layer5 and SMP logo
image

### corrected the social icons in footer
image

### CODE REVIEW

**Comment by vedant-kakde** [comment]
LGTM 👍🏻 Great work  @akshatnema

**Review by vedant-kakde — APPROVED** [review]

**Comment by amino19** [comment]
@akshatnema: Thanks for your contribution, just one thing to ask, whether we shall reduce the `upper icon` according to the mobile view?

If we can, then let's make it better possible, by aligning further icons to `center` by reducing the size of `upper icon`.
If not, then we're good to go! :eyes: 

image

**Comment by akshatnema** [comment]
@amino19, will this be okay?
image

**Comment by warunicorn19** [comment]
@amino19 thank you for the review, i was about to write the exact same thing😅

**Comment by warunicorn19** [comment]
@

> @amino19, will this be okay? image

@akshatnema let's get it completely centered with the above text.

**Comment by akshatnema** [comment]
@warunicorn19 @amino19, is this okay?
image

**Comment by warunicorn19** [comment]
yup perfect @akshatnema

**Review by amino19 — APPROVED** [review]
@akshatnema: Thanks, looks good to me! :partying_face:

**Comment by akshatnema** [comment]
@vedant-kakde @warunicorn19, I have done all the changes requested. Kindly have a look into it.

**Comment by amino19** [comment]
> @vedant-kakde @warunicorn19, I have done all the changes requested. Kindly have a look into it.

@akshatnema: It would be better to attach a final preview of the recent commit. WDYT?

**Comment by vedant-kakde** [comment]
@amino19 preview will be visible after the maintainer approves the workflows. Don't worry about that.

**Review by warunicorn19 — APPROVED** [review]
Thank you @akshatnema

**Review by vedant-kakde — APPROVED** [review]

**Comment by amino19** [comment]
> @amino19 preview will be visible after the maintainer approves the workflows. Don't worry about that.

First thing, I'm not worried.
Second, as a web developer, we must have concerned to re-check the changes, whether it will be initial/ final commits.

"As a good contributor, we always need to present our work to folks who're reviewing & maintainers as well. So, they can feel free to merge while reviewing! :slightly_smiling_face: "

I hope you understand now, better if you once go through [CONTRIBUTING.md](https://github.com/service-mesh-performance/service-mesh-performance/blob/master/CONTRIBUTING.md) guidelines, to test service mesh performance website locally.

**Comment by akshatnema** [comment]
## Preview Changes

Aligned the LAYER5 logo with text and center-aligned the SMP logo.
image

Corrected the alignment of social icons in the footer
image

**Review by amino19 — APPROVED** [review]
@akshatnema: Cool, final commit approved. :tada:

**Review by navendu-pottekkat — APPROVED** [review]

**Pull request merged**
