### PR TITLE
added meshmark on navigation

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Related issues - responsiveness on MesHMark page. image

**Comment by leecalcote** [comment]
Does the inclusion of MeshMark in the menu cause an overflow? Are there too many items in the menu?

**Comment by asubedy** [comment]
> Does the inclusion of MeshMark in the menu cause an overflow? Are there too many items in the menu?

Yes I also think so, we can see What SMP wrapping up.

**Comment by asubedy** [comment]
> Related issues - responsiveness on MesHMark page. image

yes working on this.

**Comment by asubedy** [comment]
@leecalcote I propose that we remove the `Resources` item from the navigation menu.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
