### PR TITLE
ServiceMeshCon-EU 2021 video added

### LINKED ISSUE #234: Add ServiceMeshCon-EU 2021 video to smp-spec site
Service mesh performance in general and specifically the SMP project has been discussed in the ServiceMeshCon-EU conference recently. Would be good to add the recorded video posted by CNCF to the smp-spec.io site.

**Desired State of the service-mesh-performance site**
Video URL: https://www.youtube.com/watch?v=RXmgOsSxrSg&feature=youtu.be 

This video is hosted at appropriate section of the smp home page.

### PR DESCRIPTION
**Pull request by Rishi22-Coding**
Signed-off-by: Saptarshi Patra
**Description**
ServiceMeshCon-EU 2021 video has been added.

This PR fixes #234 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
I think this looks okay, thanks @Rishi22-Coding  // @soham4abc @leecalcote thoughts?

**Comment by leecalcote** [comment]
Good stuff. This latest talk show be placed in chronological order - after the other two before it.

**Comment by soham4abc** [comment]
> I think this looks okay, thanks @soham4abc. // @leecalcote thoughts?

LGTM!

**Review by leecalcote — CHANGES_REQUESTED** [review]
These are still showing in the wrong order.

**Comment by Rishi22-Coding** [comment]
@leecalcote sir for better understanding I have question. Should i place the latest talk show after (KubeCon EU 2019 - Lee Calcote & Girish Ranganathan) - this video?

**Comment by Rishi22-Coding** [comment]
@warunicorn19  hi , can you help me how to maintain the chronology order? I mean where to insert that talk show?

**Review by warunicorn19 — APPROVED** [review]
Changes LGTM 🎉, Thanks @Rishi22-Coding, Let's wait for what @leecalcote says.

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Rishi22-Coding will you have a look at the merge conflict here - https://github.com/service-mesh-performance/service-mesh-performance/pull/235/conflicts?

**Review by warunicorn19 — APPROVED** [review]

**Review by warunicorn19 — APPROVED** [review]

**Review by sayantan1413 — APPROVED** [review]

**Comment by warunicorn19** [comment]
Yup it's good to merge.

**Pull request merged**
