### PR TITLE
ci(lint): Fix golint error

### LINKED ISSUE #435: Fixing CI Piplines
Currently, there are some issues in CI piplines. We need to fix them and delete unneccessary piplines..

### PR DESCRIPTION
**Pull request by lekaf974**
**Description**

This PR fixes #435

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by lekaf974** [comment]
@gyohuangxin ready for another try

**Comment by lekaf974** [comment]
@gyohuangxin new attempt

**Comment by lekaf974** [comment]
@gyohuangxin here we go 
if you check the first steps it works as expected, the golonglint-ci action also covering the following linters by default so we can remove duplicates:
- errcheck 
- gosimple 
- govet 
- ineffassign 
- staticcheck 
- unused

see here https://github.com/service-mesh-performance/service-mesh-performance/actions/runs/10646469733/job/29522941402#step:5:27 

starting to work on test part

**Comment by gyohuangxin** [comment]
@lekaf974 Great jobs!

**Comment by lekaf974** [comment]
@gyohuangxin new update

- remove duplicate action
- Attempt fix kind cluster creation

**Comment by gyohuangxin** [comment]
@lekaf974 The CI piplines are green. Thanks for your great contribution 👍 👍 👍

**Review by gyohuangxin — APPROVED** [review]
LGTM

**Pull request merged**
