### PR TITLE
[Dashboard] Updates on the Dashboard

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
The following PR will address the following changes:
1. Remove the Load time when going to new page on the table view
2. Show all the missing value of the test Specifications
3. Change the color of the headers on the individual results page
4. Changed profiles card formatting 
5. Change the title of the individual results from `2022-08-15-22.15.08` to `15th August 2022, 22:15:08 UTC` [WIP] [Suggestion Needed]

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by asubedy** [comment]
@gyohuangxin could you suggest on the title of the individual result? Is my approach on naming it appropriate?

**Comment by gyohuangxin** [comment]
@asubedy Thanks for raising this PR, I think it is still not meaningful to change the title of the individual results from `2022-08-15-22.15.08` to `15th August 2022, 22:15:08 UTC`. Can we name it to the profile name as we discussed from  https://github.com/layer5io/meshery-smp-action/issues/59?

**Comment by asubedy** [comment]
@gyohuangxin So maybe like `Istio Load Test with Fortio 15th Aug 2022 9 PM ` ? I think date and time would be necessary if we are prefixing all the individual results with same name. But I also think this way the name becomes too long

**Comment by gyohuangxin** [comment]
In my opinion, the datetime in title may be not necessary, we can find the results via the datetime in `Last Run` column.

**Comment by asubedy** [comment]
@gyohuangxin Please have a look, I have changed the profile name formatting as discussed
image

**Comment by gyohuangxin** [comment]
@asubedy Awesome! It looks great. cc @leecalcote @hershd23

**Review by gyohuangxin — APPROVED** [review]
LGTM

**Comment by gyohuangxin** [comment]
@asubedy Is this PR ready to be merged?

**Pull request merged**
