### PR TITLE
Fixed the Slack Notify on star

### LINKED ISSUE #236: [CI] Slack workflow
**Description**
The slack star workflow seems to be failing

**Expected Behavior**
Well, it shouldn't

### PR DESCRIPTION
**Pull request by SirZeck**
**Description**

This PR fixes #236 

**Notes for Reviewers**
The star counts on the repo wasn't being notified to slack channel. I checked the meshery repo for slack.yml and made the right changes I think that will fix the issue. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ Aditya Raj] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
Good work, @SirZeck. From next time if you could do all this in a lesser no. of commits, so many commits for a small issue is not preferred.

**Review by leecalcote — CHANGES_REQUESTED** [review]
@SirZeck there's no need for the if statement. Let's stick with the same logic that is used in this workflow across the other 50+ repos. Will you refactor?

**Comment by SirZeck** [comment]
> @SirZeck there's no need for the if statement. Let's stick with the same logic that is used in this workflow across the other 50+ repos. Will you refactor?

Okay @leecalcote I'll refactor it.

**Comment by lohityarra** [comment]
Hey, the issue is still there. I just joined the slack community and this happened. I'm adding a screenshot if that is helpful.

Screenshot:
Screenshot (3620)

**Comment by leecalcote** [comment]
@lohityarra yikes!

**Comment by leecalcote** [comment]
@SirZeck no sweat. :thu

**Pull request closed without merging**
