### PR TITLE
AddedIntelLogo

### LINKED ISSUE #166: [Site] Add Intel logo to contributors section of website
**Current Behavior**
Individuals at Intel have joined the Service Mesh Performance initiative.

**Desired Behavior**
Intel's participation should be represented in the Contributors section of the website.

### PR DESCRIPTION
**Pull request by SaimBonda**
**Description**
Added Intel Logo to Contributors Section

This PR fixes #166

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @BondaSaim. Very good.

**Comment by BondaSaim** [comment]
@leecalcote Thank you for the opportunity sir

**Review by soham4abc — CHANGES_REQUESTED** [review]
slide.css change bot mentioned in the PR.

**Comment by adithyaakrishna** [comment]
@soham4abc & @SaimBonda Any updates on this or is this ready for review? 👀

**Comment by Jashpatel1** [comment]
@soham4abc @SaimBonda Any progress here?

**Review by soham4abc — APPROVED** [review]

**Comment by sunkuranganath** [comment]
Got a yes from our team to have the logo listed in the "Contributor" section.
We are good to go on this.

**Comment by leecalcote** [comment]
Whoo-hoo!

**Review by leecalcote — APPROVED** [review]
Thank you for this effort, @SaimBonda 👍

**Pull request merged**
