### PR TITLE
Contributing instructions updated

### LINKED ISSUE #229: [Chore] Contributing instructions update
Update the CONTRIBUTING.md to say that SMP prominently and consistently engages with the Meshery project. For a more complete set of contributing guides see docs.meshery.io/project/contributing.

### PR DESCRIPTION
**Pull request by Rishi22-Coding**
Signed-off-by: Saptarshi Patra

**Description**
Contributing instructions updated
This PR fixes #229 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sayantan1413 — CHANGES_REQUESTED** [review]
I think it would be better to shift the change under the `Contributing Overview` section.

**Comment by Rishi22-Coding** [comment]
Okay let me do it.

**Comment by Rishi22-Coding** [comment]
@sayantan1413  @warunicorn19 I'm really very sorry to work on this issue which was assigned to @sayantan1413. Actually i didn't used to github, And I didn't know how things are work in open-source community. It took me sometime to familiarized. @sayantan1413 If you want i can delete this branch and work on another issue which isn't assigned to someone.

**Comment by warunicorn19** [comment]
Hey, @Rishi22-Coding it's no big deal, I'm pretty sure @sayantan1413 doesn't mind😅. You don't have to delete this.

**Comment by sayantan1413** [comment]
Hey @Rishi22-Coding  it is absolutely okay, you don't have to delete the branch😅. But from the next time have a look at the assignees tab, and if you find anyone is assigned there please ask the contributor if you could help the contributor. So that none of our work goes in vain 😅. By the way good work here @Rishi22-Coding 🎉🚀

**Comment by Rishi22-Coding** [comment]
Thanks a lot. I will keep that in mind.😅

**Review by warunicorn19 — APPROVED** [review]
Yup good work here @Rishi22-Coding , thanks

**Review by sayantan1413 — APPROVED** [review]
LGTM !

**Review by leecalcote — APPROVED** [review]
Thanks, @Rishi22-Coding 👍

**Comment by leecalcote** [comment]
@Rishi22-Coding you're most welcome to join the open source community at Layer5 --> https://layer5.io/community/newcomers

**Pull request merged**
