### PR TITLE
Presentation video alignment fix

### LINKED ISSUE #363: alignment of the embed video
Current State of the service-mesh-performance site
Current Design - https://smp-spec.io/  of the embedded video. 

#### Desired State of the service-mesh-performance site
We can change the position as seen in the screenshot.
Screenshot 2023-01-07 at 12 19 32

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by MrBehl06**
**Description**

This PR fixes #363 Alignment fixed 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by GaganpreetKaurKalsi** [comment]
Looks good @MrBehl06 👍

**Comment by MrBehl06** [comment]
@GaganpreetKaurKalsi Thank you

**Review by gyohuangxin — APPROVED** [review]
@MrBehl06 Thanks, lgtm.

**Review by asubedy — APPROVED** [review]
LGTM

**Pull request merged**
