### PR TITLE
MeshMark Landing Page

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@leecalcote @asubedy updated the feedback.

**Comment by asubedy** [comment]
image

The tagline and short description could be place little below, so that it aligns with the `MeshMark` text  on the left

**Review by leecalcote — CHANGES_REQUESTED** [review]
Screen Shot 2022-05-16 at 12 49 01 PM

**Review by Abhishek-kumar09 — APPROVED** [review]
This page looks dope.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
A link to MeshMark needs to be exposed on the main page and/or in the nav-links.

**Pull request merged**
