### PR TITLE
Add schema for better SEO

### LINKED ISSUE #259: Add schema to the website for better SEO
**Current State of the service-mesh-performance site**
Add schema to the website for better SEO.

Refer: https://schema.org/docs/schemas.html
Implementation in Layer5's website: https://github.com/layer5io/layer5/blob/master/src/pages/index.js#L26

Schema validator: https://validator.schema.org/

**Desired State of the service-mesh-performance site**
A brief description of the change you are requesting.

### PR DESCRIPTION
**Pull request by toth2000**
Signed-off-by: toth2000 <tothagata.bhattacharjee@gmail.com>

**Description**
Add schema for better SEO

This PR fixes #259 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by navendu-pottekkat — COMMENTED** [review]
The schema is working fine. Really great additions here.

Screenshot 2021-11-08 at 9 47 44 AM

A couple of changes needed:

1. Parent organisation is Cloud Native Computing Foundation (CNCF)
2. Is there another object type other than sponsor? Because sponsor sounds like there is monetary involvement.
3. A different type than "corporation"? In the meshery.io site we mention it as "website" but any better alternative would also work.

**Comment by leecalcote** [comment]
Layer5 works as the sponsor.

**Comment by toth2000** [comment]
Pushed new commits implementing the suggested changes.

**Review by leecalcote — APPROVED** [review]
Lgtm

**Pull request merged**
