### PR TITLE
Fix 404 Resources

### LINKED ISSUE #254: Incorrect resource URLs
**Description**

`unsubscribed` page uses a relative url when asking for css and js resources which point to `unsubscribed/assets/css/responsive.css`

**Expected Behavior**

The resource should point to `/assets/css/responsive.css`

**Screenshots**

image

**Environment:**
 - OS: Manjaro
 - Browser: Brave
 - Version: 1.29.79-1
 - Device: Laptop

---
[Optional] **To Reproduce**
1. Go to https://smp-spec.io/unsubscribed/
2. Click on open the developer tools
3. Open the networks tab

### PR DESCRIPTION
**Pull request by king-11**
**Description**

- fix: use absolute URLs for assets
- fix: navbar prev unused assets removed

This PR fixes #254

**Notes for Reviewers**

If needed, we can comment the previous navbar, but that seems unnecessary, so was cleaned off

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by king-11** [comment]
@leecalcote awaiting your review on this

**Comment by king-11** [comment]
@leecalcote any updates?

**Comment by mganguli** [comment]
this change looks good. would be good to also have a "name" version instead of the URL

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thank you @king-11

**Pull request merged**
