### PR TITLE
Update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by leecalcote**
Updating @utkarsh-pro and @navendu-pottekkat's status.

### CODE REVIEW

**Review by utkarsh-pro — APPROVED** [review]
Thank you @leecalcote 🙂 .

**Comment by leecalcote** [comment]
@utkarsh-pro thank you for all of your time spent on this project. 👏

**Comment by navendu-pottekkat** [comment]
@leecalcote today is my last day away from the community and the projects. In regard to our previous discussion as to not have me present myself with a false sense of availability, I have tried not to involve in the projects until I am back for good.

I am sure I would be able to continue my role here as maintainer and steward initiatives in and around the project.

**Comment by leecalcote** [comment]
@navendu-pottekkat adding you back in. Please note the updated governance.md requirements for maintainers.

**Pull request merged**
